name: Checks
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - run: |
        pip install --upgrade pip
        pip install black==21.6b0 pylint==v3.0.0a3 mypy==v0.902
        black --diff --check jsonrpcserver
        pylint --disable=all --enable=unused-import jsonrpcserver
        mypy --disallow-untyped-defs --disallow-untyped-calls --check-untyped-defs jsonrpcserver
